### ISSUE TITLE
Crash with Sponge server

### ISSUE THREAD

**Issue by LordDarthDan** [LubieKakao1212/OpenCombatUtility#2]
Hi again.

I know you're working on 1.18 rn but I'm posting this here just in case, up to you if you wanna do anything with it.
Tried launching a pack with OpenCU on a (Sponge) server, and got an on-launch error:
`[16:18:57] [Server thread/ERROR] [FML]: An error occurred trying to load an EventBusSubscriber com.LubieKakao1212.opencu.event.TooltipEventHandler for modid opencu
java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag`
Full log attached.
[2023-01-24-6.log](https://github.com/LubieKakao1212/OpenCombatUtility/files/10494278/2023-01-24-6.log)

This _looks_ like some client side code trying to run server side to me, but I'm sure you know more than I do.

**Comment by LubieKakao1212** [comment]
Should be fixed in the next update

**Comment by LordDarthDan** [comment]
Server works, thanks a ton for fixing this so fast!
